=== LEAF-HQ/ZTo2Mu2Tau/Plotter/PlotterConfiguration.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>


<!ELEMENT PlotterConfiguration (FileConfiguration, PlottingConfiguration,InputDatasets)>


<!ELEMENT FileConfiguration EMPTY>
<!ATTLIST  FileConfiguration
    OutputDirectory      CDATA            #REQUIRED
    InputDirectory       CDATA            #REQUIRED
    SEDirector           CDATA            #REQUIRED
    PreFix               CDATA            ""
>

<!ELEMENT PlottingConfiguration EMPTY>
<!ATTLIST  PlottingConfiguration
    blind         CDATA     #REQUIRED
    logY          CDATA     #REQUIRED
    normalize     CDATA     #REQUIRED
    singlePDF     CDATA     #REQUIRED
    lumitext      CDATA     #REQUIRED
    numerator     CDATA     #REQUIRED
>


<!ELEMENT InputDatasets (Dataset+)>

<!ELEMENT Dataset EMPTY>
<!ATTLIST Dataset
    Name        CDATA         #REQUIRED
    Color       CDATA         #REQUIRED
    Linestyle   CDATA         #REQUIRED
    Legend      CDATA         #REQUIRED
    Type        (MC|DATA)     #REQUIRED
    Stack       (true|false)  #REQUIRED
    ScaleFactor CDATA         ""
>

=== LEAF-HQ/ZTo2Mu2Tau/Plotter/Default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PlotterConfiguration PUBLIC "" "PlotterConfiguration.dtd"[]>


<PlotterConfiguration>

  <FileConfiguration
    InputDirectory  = "/work/areimers/CMSSW_10_6_28/src/LEAF/../../../ZTo2Mu2Tau/2017/Preselection/InitialSetup"
    OutputDirectory = "/work/areimers/CMSSW_10_6_28/src/LEAF/../../../ZTo2Mu2Tau/2017/Preselection/InitialSetup/plots/distributions"
    PreFix          = "TestAnalysis_"
    SEDirector      = "root://t3dcachedb03.psi.ch/"
  />

  <PlottingConfiguration
    lumitext   = "41.5 fb^{-1} (13 TeV)"
    blind      = "false"
    logY       = "true"
    normalize  = "false"
    singlePDF  = "false"
    numerator  = "TestData"
  />

  <InputDatasets>
    <Dataset Name="TestSignal_M1000"   Stack="false"  Color="1"    Linestyle="2"   Legend="Test signal (M = 1000 GeV)"   Type="MC" />
    <Dataset Name="TestSignal_M2000"   Stack="false"  Color="1"    Linestyle="1"   Legend="Test signal (M = 2000 GeV)"   Type="MC" />
    <Dataset Name="TestBackground"    Stack="true"   Color="814"  Linestyle="0"   Legend="Test background"              Type="MC" />
    <Dataset Name="TestData"          Stack="false"  Color="1"    Linestyle="0"   Legend="Test data"                    Type="DATA" />
  </InputDatasets>


<!--
kWhite    0,
kBlack    1,
kYellow   400
kGreen    416
kCyan     432
kBlue     600
kMagenta  616
kRed      632
kOrange   800
kSpring   820
kTeal     840
kAzure    860
kViolet   880
kPink     900
kGray     920

-->



</PlotterConfiguration>
